GET https://cse-341-project1-t08e.onrender.com/
###
GET https://cse-341-project1-t08e.onrender.com/contacts
###
GET https://cse-341-project1-t08e.onrender.com/contacts/67ca0aa706dd9a333bc7be0f
###
POST https://cse-341-project1-t08e.onrender.com/contacts/
Content-Type: application/json

{
    "firstName": "José Carlos",
    "lastName": "Pereira",
    "email": "jcpereira@example.com",
    "favoriteColor": "red",
    "birthday": "03/01/2000"
}
###
PUT https://cse-341-project1-t08e.onrender.com/contacts/67d53a449f530a551c5a8622
Content-Type: application/json

{
    "firstName": "Andre",
    "lastName": "Silveira",
    "email": "asilvairae@example.com",
    "favoriteColor": "white",
    "birthday": "03/06/1996"
}
###
DELETE https://cse-341-project1-t08e.onrender.com/contacts/67ca0aa706dd9a333bc7be0f
Content-Type: application/json

{
    "firstName": "Mauro",
    "lastName": "Santos",
    "email": "msantose@example.com",
    "favoriteColor": "Orange",
    "birthday": "03/01/2000"
}


